//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCLRun
{
    using System;
    
    public partial class BulkJob
    {
        public int BulkJobID { get; set; }
        public int ClientID { get; set; }
        public string ClientCode { get; set; }
        public string JobNumber { get; set; }
        public string DeliveryDate { get; set; }
        public string ReadyTime { get; set; }
        public int JobStatus { get; set; }
        public string CompanyName { get; set; }
        public string ToAddress { get; set; }
        public string ToSuburb { get; set; }
        public Nullable<int> CourierID { get; set; }
        public string FromCompany { get; set; }
        public string FromAddress { get; set; }
        public string FromSuburb { get; set; }
        public string Contact { get; set; }
        public decimal Amount { get; set; }
        public int SpeedID { get; set; }
        public Nullable<short> Size { get; set; }
        public Nullable<short> Items { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<bool> RemoteScreen { get; set; }
        public string ClientRefa { get; set; }
        public string ClientRefb { get; set; }
        public string OurRef { get; set; }
        public Nullable<bool> Ok_To_Leave { get; set; }
        public Nullable<int> Location { get; set; }
        public string Notes { get; set; }
        public Nullable<int> TrackingMethod { get; set; }
        public string TrackingEmail { get; set; }
        public string TrackingMobile { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<double> fromLat { get; set; }
        public Nullable<double> fromLng { get; set; }
        public Nullable<double> toLng { get; set; }
        public Nullable<double> toLat { get; set; }
        public Nullable<bool> PrebookJob { get; set; }
        public Nullable<bool> WellingtonJob { get; set; }
        public Nullable<bool> NWDocJob { get; set; }
        public bool Done { get; set; }
        public bool Void { get; set; }
        public int ToPostCode { get; set; }
        public Nullable<int> FromPostCode { get; set; }
        public string DeliverToContact { get; set; }
        public string DeliverToPhone { get; set; }
        public Nullable<int> FromGeoType { get; set; }
        public Nullable<int> ToGeoType { get; set; }
        public string RunName { get; set; }
        public int BulkJobRunID { get; set; }
        public string Courier { get; set; }
        public Nullable<int> BuilderIndex { get; set; }
        public string PrefixRunName { get; set; }
        public int MaxJobsPerRun { get; set; }
        public Nullable<int> MultiboxParentID { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> JobRelationshipTypeId { get; set; }
    }
}
