//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCLRun
{
    using System;
    
    public partial class BulkRun
    {
        public Nullable<int> CourierID { get; set; }
        public int BulkJobID { get; set; }
        public int ID { get; set; }
        public string name { get; set; }
        public string Courier { get; set; }
        public string Fleet { get; set; }
        public string CourierPercentage { get; set; }
        public Nullable<int> Mins { get; set; }
        public Nullable<double> Kms { get; set; }
        public int RunOrder { get; set; }
    }
}
