//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCLRun
{
    using System;
    
    public partial class PotentialCouriers
    {
        public int courierID { get; set; }
        public string courier { get; set; }
        public string Fleet { get; set; }
    }
}
