//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCLRun
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBulkJob
    {
        public int BulkJobID { get; set; }
        public string JobNumber { get; set; }
        public System.DateTime BookDate { get; set; }
        public System.DateTime BookTime { get; set; }
        public int JobStatus { get; set; }
        public int ClientID { get; set; }
        public string ClientCode { get; set; }
        public string Contact { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public int Speed { get; set; }
        public string FromCompany { get; set; }
        public string FromAddress { get; set; }
        public string FromSuburb { get; set; }
        public string ToCompany { get; set; }
        public string ToAddress { get; set; }
        public string ToSuburb { get; set; }
        public Nullable<short> Size { get; set; }
        public Nullable<short> Qty { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> CourierID { get; set; }
        public string ClientRefa { get; set; }
        public string ClientRefb { get; set; }
        public string OurRef { get; set; }
        public Nullable<bool> DeliverToPrivateBusiness { get; set; }
        public Nullable<int> DeliverToLeaveID { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> RemoteJob { get; set; }
        public Nullable<int> TrackingMethod { get; set; }
        public string TrackingEmail { get; set; }
        public string TrackingMobile { get; set; }
        public string ProofOfDeliveryMobile { get; set; }
        public string ProofOfDeliveryEmail { get; set; }
        public string PickUpLatitude { get; set; }
        public string PickUpLongitude { get; set; }
        public string DeliveryLatitude { get; set; }
        public string DeliveryLongitude { get; set; }
        public Nullable<bool> PrebookJob { get; set; }
        public Nullable<bool> WellingtonJob { get; set; }
        public Nullable<bool> NWDocJob { get; set; }
        public bool Done { get; set; }
        public bool Void { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<int> FromPostCode { get; set; }
        public Nullable<int> ToPostCode { get; set; }
        public bool OnHold { get; set; }
        public string DeliverToContact { get; set; }
        public string DeliverToPhone { get; set; }
        public string RunName { get; set; }
        public Nullable<int> FromGeoType { get; set; }
        public Nullable<int> ToGeoType { get; set; }
        public string Manifest { get; set; }
    }
}
