// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoutedOperations.Core.Domain.Despatch;

public partial class BulkImportBatch
{
    public int Id { get; set; }

    public DateTime Created { get; set; }

    public int ContactId { get; set; }

    public virtual TucClientContact Contact { get; set; }

    public virtual ICollection<TblBulkJob> TblBulkJobs { get; set; } = new List<TblBulkJob>();
}
