// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoutedOperations.Core.Domain.Despatch;

public partial class BulkZonePostcodeSurcharge
{
    public int Id { get; set; }

    public int PostCode { get; set; }

    public int? ClientId { get; set; }

    public decimal? Surcharge { get; set; }

    public virtual TucClient Client { get; set; }
}
