// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoutedOperations.Core.Domain.Despatch;

public partial class BulkZonePostcode
{
    public int Id { get; set; }

    public DateTime Created { get; set; }

    public int Zone { get; set; }

    public int PostCode { get; set; }

    public int FromSiteId { get; set; }

    public string Name { get; set; }

    public int? DepotId { get; set; }

    public string FromLatLng { get; set; }

    public int? PostcodeGroupId { get; set; }

    public virtual TblBulkRegion Depot { get; set; }
    public virtual BulkZonePostcodeGroup PostcodeGroup { get; set; }
}
