// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoutedOperations.Core.Domain.Despatch;

public partial class BulkImportTemplateMapping
{
    public int Id { get; set; }

    public DateTime Created { get; set; }

    public int TemplateId { get; set; }

    public string UrgentField { get; set; }

    public string ImportField { get; set; }

    public virtual BulkImportTemplate Template { get; set; }
}
