// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoutedOperations.Core.Domain.Despatch;

public partial class BulkZoneSchedule
{
    public int Id { get; set; }

    public int Zone { get; set; }

    public int? ScheduleId { get; set; }

    public bool? Active { get; set; }

    public virtual TblBulkRunSchedule Schedule { get; set; }
}
