// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoutedOperations.Core.Domain.Despatch;

public partial class BulkImportSpeed
{
    public int Id { get; set; }

    public DateTime Created { get; set; }

    public int SpeedId { get; set; }

    public int? ClientId { get; set; }

    public virtual TucClient Client { get; set; }

    public virtual TucJobType Speed { get; set; }
}
