// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoutedOperations.Core.Domain.Despatch;

public partial class BulkImportJobNumber
{
    public int JobNumberId { get; set; }

    public string JobNumberName { get; set; }

    public int? JobNumberIncrement { get; set; }
}
