// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoutedOperations.Core.Domain.Despatch;

public partial class BulkImportTemplate
{
    public int Id { get; set; }

    public DateTime Created { get; set; }

    public int ContactId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<BulkImportTemplateMapping> BulkImportTemplateMappings { get; set; } = new List<BulkImportTemplateMapping>();

    public virtual TucClientContact Contact { get; set; }
}
