// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoutedOperations.Core.Domain.Despatch;

public partial class JobDeliveryJourney
{
    public int JourneyId { get; set; }

    public int JobId { get; set; }

    public string ChangeType { get; set; }

    public int? OldInternalStatusId { get; set; }

    public int? NewInternalStatusId { get; set; }

    public int? OldJobStatusId { get; set; }

    public int? NewJobStatusId { get; set; }

    public int? FlightId { get; set; }

    public int? OldAgentId { get; set; }

    public int? NewAgentId { get; set; }

    public int? OldCourierId { get; set; }

    public int? NewCourierId { get; set; }

    public string FieldName { get; set; }

    public string OldValue { get; set; }

    public string NewValue { get; set; }

    public int? StaffId { get; set; }

    public int? CourierId { get; set; }

    public string UpdatedByType { get; set; }

    public DateTime UpdatedAt { get; set; }

    public string Comments { get; set; }

    public virtual TucCourier Courier { get; set; }

    public virtual TucJob Job { get; set; }

    public virtual TucCourier NewCourier { get; set; }

    public virtual TucJobStatus NewJobStatus { get; set; }

    public virtual TucCourier OldCourier { get; set; }

    public virtual TucJobStatus OldJobStatus { get; set; }
}
