// Hand-authored extension of the auto-scaffolded TblbulkLinehaulRun entity.
// The base file (TblbulkLinehaulRun.cs) is generated by EF Core Power Tools
// from the current DB shape. These four columns + the matching navigation
// properties were added to the shared Despatch DB by earlier Configurator
// migrations and confirmed present on both DFRNT_SEED_CR (US) and
// Despatch_Urgent_Staging (NZ) via MCP on 2026-08-12.
//
// Kept in this partial (not in the base auto-scaffold file) so a future
// Power Tools regen cannot silently drop the new properties. The FK / index
// fluent config for these columns lives in DynamicDespatchDbContext.OnModelCreating.
#nullable disable
using System.Collections.Generic;

namespace RoutedOperations.Core.Domain.Despatch;

public partial class TblbulkLinehaulRun
{
    // Polymorphic default target (Recurring Routes Fixes 5). Byte codes:
    // 1 = Courier, 2 = Agent, 3 = NetworkPartner. NULL when the run is unbound.
    // Agent + NP both resolve via DefaultAgentId; the type byte records the
    // operator's choice so the UI shows the right chip colour.
    public byte? DefaultTargetType { get; set; }

    // FK to TucAgent for Agent + NP default targets. Courier defaults still
    // land in the pre-existing CourierId column.
    public int? DefaultAgentId { get; set; }

    // Run-level Speed override (TucJobType.UcjtId). NULL means inherit whichever
    // speed the schedule leg specifies. Recurring Routes Fix 8.
    public int? SpeedId { get; set; }

    // 1 = Road (default), 2 = Flight. A Flight run must carry a flight-grouped
    // Speed; the run's SpeedId overrides the schedule at booking time so the
    // realised master + child jobs inherit a flight-grouped speed and route
    // through the existing DespatchWeb flight path with no SP change.
    public byte Mode { get; set; }

    public virtual TucAgent DefaultAgent { get; set; }

    public virtual TucJobType Speed { get; set; }

    public virtual ICollection<DispatchLinehaulRunRoster> DispatchLinehaulRunRosters { get; set; }
        = new List<DispatchLinehaulRunRoster>();
}
