// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoutedOperations.Core.Domain.Despatch;

public partial class TblbulkLinehaulRun
{
    public int Id { get; set; }

    public string RunName { get; set; }

    public int FromDepotId { get; set; }

    public int ToDepotId { get; set; }

    public TimeOnly? StartTime { get; set; }

    // Nullable to match the on-disk schema (verified 2026-08-12 via MCP on both
    // DFRNT_SEED_CR and Despatch_Urgent_Staging: CourierID is IS_NULLABLE=YES).
    // The base auto-scaffold generated `int` from a stale snapshot; a Power Tools
    // regen against the current DB would produce this same `int?` shape.
    public int? CourierId { get; set; }

    public TimeOnly? DespatchTime { get; set; }

    public virtual TucCourier Courier { get; set; }

    public virtual TblBulkRegion FromDepot { get; set; }

    public virtual ICollection<TblBulkScheduleLinehaul> TblBulkScheduleLinehauls { get; set; } = new List<TblBulkScheduleLinehaul>();

    public virtual TblBulkRegion ToDepot { get; set; }
}
