// Ported from RunBuilder\Models\TblBulkJob.cs (auto-generated by EF Power Tools).
// Kept as a flat property bag to match the legacy schema exactly; the columns
// the RunBuilder cockpit reads/writes are all here. Additional columns can be
// added later without breaking downstream mappers.
#nullable disable
namespace RoutedOperations.Core.Domain.Despatch;

public partial class TblBulkJob
{
    public int BulkJobId { get; set; }
    public string JobNumber { get; set; }
    public DateTime BookDate { get; set; }
    public DateTime BookTime { get; set; }
    public int JobStatus { get; set; }
    public int ClientId { get; set; }
    public string ClientCode { get; set; }
    public string Contact { get; set; }
    public decimal? Amount { get; set; }
    public int Speed { get; set; }
    public string FromCompany { get; set; }
    public string FromAddress { get; set; }
    public string FromSuburb { get; set; }
    public int? FromPostCode { get; set; }
    public string ToCompany { get; set; }
    public string ToAddress { get; set; }
    public string ToSuburb { get; set; }
    public int? ToPostCode { get; set; }
    public int? Size { get; set; }
    public short? Qty { get; set; }
    public decimal? Weight { get; set; }
    public int? CourierId { get; set; }
    public string ClientRefa { get; set; }
    public string ClientRefb { get; set; }
    public string OurRef { get; set; }
    public bool? DeliverToPrivateBusiness { get; set; }
    public int? DeliverToLeaveId { get; set; }
    public string Notes { get; set; }
    public bool? RemoteJob { get; set; }
    public int? TrackingMethod { get; set; }
    public string TrackingEmail { get; set; }
    public string TrackingMobile { get; set; }
    public string ProofOfDeliveryMobile { get; set; }
    public string ProofOfDeliveryEmail { get; set; }
    public string PickUpLatitude { get; set; }
    public string PickUpLongitude { get; set; }
    public string DeliveryLatitude { get; set; }
    public string DeliveryLongitude { get; set; }
    public bool? PrebookJob { get; set; }
    public bool OnHold { get; set; }
    public bool? WellingtonJob { get; set; }
    public bool? NwdocJob { get; set; }
    public bool Done { get; set; }
    public bool Void { get; set; }
    public int? JobId { get; set; }
    public string DeliverToContact { get; set; }
    public string DeliverToPhone { get; set; }
    public string RunName { get; set; }
    public int? FromGeoType { get; set; }
    public int? ToGeoType { get; set; }
    public string Manifest { get; set; }
    public int? RunOrder { get; set; }
    public int? BulkRunId { get; set; }
    public int? ImportId { get; set; }
    public bool? Multibox { get; set; }
    public decimal? Length { get; set; }
    public decimal? Width { get; set; }
    public decimal? Height { get; set; }
    public int? MultiboxParentId { get; set; }
    public decimal? CourierPayment { get; set; }
    public bool? SortScan { get; set; }
    public bool? RunScan { get; set; }
    public int? ScheduleId { get; set; }
    public string OrderRef { get; set; }
    public int? ShopId { get; set; }
    public string Barcode { get; set; }
    public int? JobRelationshipTypeId { get; set; }
    public int? ParentId { get; set; }
    public int? RegionId { get; set; }

    public virtual ICollection<TblBulkJobRun> TblBulkJobRuns { get; set; } = new List<TblBulkJobRun>();
}
