// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoutedOperations.Core.Domain.Despatch;

public partial class TblClientContact
{
    public int ClientContactId { get; set; }

    public int ClientId { get; set; }

    public int ContactId { get; set; }

    public string DefaultJobType { get; set; }

    public string DefaultJobSpeed { get; set; }

    public string DefaultPickupLocation { get; set; }

    public string DefaultJobSize { get; set; }

    public string DefaultPage { get; set; }

    public bool IsDefaultAccount { get; set; }

    public int? DefaultPod { get; set; }

    public string DefaultPodphone { get; set; }

    public string DefaultPodemail { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public string Notes { get; set; }

    public bool AddOnCharge { get; set; }

    public bool HoldJobs { get; set; }

    public decimal? MaxJobSpend { get; set; }

    public string DefaultPrinter { get; set; }

    public int? DefaultPrintSize { get; set; }

    public bool RotateLabel { get; set; }

    public int? DefaultClientAddressBookId { get; set; }

    public bool? DefaultSendTrackAndTraceToPodemail { get; set; }

    public bool? DefaultRotate180 { get; set; }

    public int? DefaultTrackingMethod { get; set; }

    public string DefaultTrackingMobile { get; set; }

    public string DefaultTrackingEmail { get; set; }

    public bool UseDefaultOnNewBooking { get; set; }

    public int? DefaultPackageSize { get; set; }

    public virtual TucClient Client { get; set; }

    public virtual TucClientContact Contact { get; set; }
}
