// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoutedOperations.Core.Domain.Despatch;

public partial class TblClientAvailableSpeed
{
    public int Id { get; set; }

    public int ClientId { get; set; }

    public int SpeedId { get; set; }

    public bool Active { get; set; }

    public decimal? SalePrice { get; set; }

    public bool? InternalVisible { get; set; }

    public bool? WebVisible { get; set; }

    public bool? Apivisible { get; set; }

    public bool? BookImmediate { get; set; }

    public int? ProcessingTime { get; set; }

    public string Description { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public string DisplayName { get; set; }

    public string Weekday { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public decimal? Markup { get; set; }

    public bool? UseSchedules { get; set; }

    public int? DaysInFuture { get; set; }

    public decimal? AddonPercentage { get; set; }

    public int? NoSdailyLimit { get; set; }

    public decimal? CourierPercentage { get; set; }

    public decimal? FuelPercentage { get; set; }

    public bool? Mfv { get; set; }

    public bool? Faf { get; set; }

    public virtual TucClient Client { get; set; }

    public virtual TucJobType Speed { get; set; }
}
