// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoutedOperations.Core.Domain.Despatch;

public partial class TblGssstockSize
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? ClientId { get; set; }

    public double Length { get; set; }

    public double Width { get; set; }

    public double Height { get; set; }

    public double Volume { get; set; }

    public double Weight { get; set; }

    public int? Sequence { get; set; }

    public bool? IsDefaultSize { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public string Notes { get; set; }
}
