// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoutedOperations.Core.Domain.Despatch;

public partial class TblSite
{
    public int SiteId { get; set; }

    public string Name { get; set; }

    public int? AirportSuburbId { get; set; }

    public string AreaCode { get; set; }

    public string DefaultSalesAccountCode { get; set; }

    public int DefaultPickupClientId { get; set; }

    public int DefaultDeliveryClientId { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public string Notes { get; set; }

    public string OldSalesAccountCode { get; set; }

    public bool? InNorthIsland { get; set; }

    public bool? CourierApplicantEnabled { get; set; }

    public string XeroTrackingOption { get; set; }

    public virtual TucSuburb AirportSuburb { get; set; }

    public virtual TucClient DefaultDeliveryClient { get; set; }

    public virtual TucClient DefaultPickupClient { get; set; }

    public virtual ICollection<TucClient> TucClients { get; set; } = new List<TucClient>();
}
