// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoutedOperations.Core.Domain.Despatch;

public partial class TucClientContact
{
    public int UcctId { get; set; }

    public int? UcctClientId { get; set; }

    public string UcctFirstname { get; set; }

    public string UcctSurname { get; set; }

    public string UcctEmail { get; set; }

    public bool HasEmail { get; set; }

    public bool ValidatedEmail { get; set; }

    public string UcctJobTitle { get; set; }

    public string UcctDirectDial { get; set; }

    public string UcctMobile { get; set; }

    public string UcctNotes { get; set; }

    public string Fax { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public bool Active { get; set; }

    public bool AllowCookieLogin { get; set; }

    public DateTime? LastAccessed { get; set; }

    public int? ContactRoleId { get; set; }

    public int? ParentContactId { get; set; }

    public bool SharedComputer { get; set; }

    public bool MustSelectChildForJob { get; set; }

    public bool EmailNotificationHasBeenSent { get; set; }

    public DateTime? WhenEmailNotificationSent { get; set; }

    public int NumberOfEmailNotificationReminderSent { get; set; }

    public DateTime? WhenLastEmailNotificationReminderSent { get; set; }

    public DateTime Created { get; set; }

    public string CreatedBy { get; set; }

    public DateTime LastModified { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime? WhenEmailValidated { get; set; }

    public DateTime? WhenEmailValidatedSent { get; set; }

    public bool PromptForEmailAddress { get; set; }

    public bool SendAdhocEmail { get; set; }

    public int? MasterBooker { get; set; }

    public string ResetKey { get; set; }

    public string Password2 { get; set; }

    public string Salt { get; set; }

    public int? StaffId { get; set; }

    public string AccessCode { get; set; }

    public virtual ICollection<BulkImportBatch> BulkImportBatches { get; set; } = new List<BulkImportBatch>();

    public virtual ICollection<BulkImportTemplate> BulkImportTemplates { get; set; } = new List<BulkImportTemplate>();

    public virtual ICollection<TblClientContact> TblClientContacts { get; set; } = new List<TblClientContact>();

    public virtual ICollection<TucJobBooking> TucJobBookings { get; set; } = new List<TucJobBooking>();

    public virtual ICollection<TucJob> TucJobs { get; set; } = new List<TucJob>();

    public virtual TucClient UcctClient { get; set; }
}
