// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoutedOperations.Core.Domain.Despatch;

public partial class TucJobBooking
{
    public int UcbkId { get; set; }

    public string UcbkJobNumber { get; set; }

    public double? UcbkDay { get; set; }

    public byte? UcbkFortnight { get; set; }

    public DateTime? UcbkTime { get; set; }

    public bool? UcbkOneOff { get; set; }

    public DateTime? UcbkDate { get; set; }

    public int? UcbkType { get; set; }

    public int? UcbkClientId { get; set; }

    public string UcbkClientCode { get; set; }

    public string UcbkClientRef { get; set; }

    public string UcbkOurRef { get; set; }

    public string UcbkContact { get; set; }

    public double? UcbkChargeType { get; set; }

    public decimal? UcbkAmount { get; set; }

    public double UcbkFrom { get; set; }

    public string UcbkFromAddr { get; set; }

    public double UcbkTo { get; set; }

    public string UcbkToSpecial { get; set; }

    public string UcbkToAddr { get; set; }

    public bool? UcbkCbd { get; set; }

    public int? UcbkSpeed { get; set; }

    public bool? UcbkDone { get; set; }

    public DateTime? UcbkDateDone { get; set; }

    public int? UcbkOperator { get; set; }

    public double? UcbkScreen { get; set; }

    public bool? UcbkActive { get; set; }

    /// <summary>
    /// Indicates who or what marked the job as inactive (User, System, Schedule, etc.)
    /// </summary>
    public int? UcbkInActiveBy { get; set; }

    public DateTime? UcbkInActiveDate { get; set; }

    public DateTime? UcbkFirstDue { get; set; }

    public DateTime? UcbkNextDue { get; set; }

    public string UcbkDays { get; set; }

    public string UcbkClientRefa { get; set; }

    public string UcbkClientRefb { get; set; }

    public int UcbkRefClientId { get; set; }

    public int? UcbkPickUpFrom { get; set; }

    public bool UcbkAttention { get; set; }

    public bool UcbkReturn { get; set; }

    public bool UcbkVan { get; set; }

    public int? UcbkWeight { get; set; }

    public int? UcbkSize { get; set; }

    public string UcbkUpdateBy { get; set; }

    public string UcbkNotes { get; set; }

    public bool SaturdayDelivery { get; set; }

    public short? Quantity { get; set; }

    public int? RefJobId { get; set; }

    public int? NumRef1 { get; set; }

    public int? NumRef2 { get; set; }

    public int? NumRef3 { get; set; }

    public int? NumRef4 { get; set; }

    public string TextRef1 { get; set; }

    public string TextRef2 { get; set; }

    public string TextRef3 { get; set; }

    public string TextRef4 { get; set; }

    public bool FixedPrice { get; set; }

    public DateTime? StopDate { get; set; }

    public DateTime? RestartDate { get; set; }

    public string ClientNotes { get; set; }

    public string InternalNotes { get; set; }

    public string PickupFromContact { get; set; }

    public string PickupFromPhone { get; set; }

    public int? DeliverToPrivateBusiness { get; set; }

    public string DeliverToContact { get; set; }

    public string DeliverToPhone { get; set; }

    public int? DeliverToLeaveId { get; set; }

    public int? ProofOfDelivery { get; set; }

    public string ProofOfDeliveryEmail { get; set; }

    public string ProofOfDeliveryMobile { get; set; }

    public int? ContactId { get; set; }

    public bool RatedManually { get; set; }

    public bool RuralDelivery { get; set; }

    public int? DesiredJobTypeId { get; set; }

    public int? AcceptedJobTypeId { get; set; }

    public bool Direct { get; set; }

    public int? NotifiedJobTypeId { get; set; }

    public int? JobRelationshipTypeId { get; set; }

    public int? ParentId { get; set; }

    public int? InformationParentId { get; set; }

    public int? RootParentId { get; set; }

    public int? BookingParentId { get; set; }

    public int? BookingInformationParentId { get; set; }

    public int? BookingRootParentId { get; set; }

    public int? CourierId { get; set; }

    public bool? AutoDespatch { get; set; }

    public bool? Parked { get; set; }

    public bool? Truck { get; set; }

    public DateTime? TruckStartTime { get; set; }

    public double? TruckHours { get; set; }

    public DateTime? RequiredDeliveryTime { get; set; }

    public bool? Reprice { get; set; }

    public decimal? PickupAmount { get; set; }

    public decimal? DropoffAmount { get; set; }

    public bool? BulletFreight { get; set; }

    public decimal? Nwamount { get; set; }

    public bool? VanOk { get; set; }

    public decimal? FuelSurchargeAmount { get; set; }

    public decimal? AgentAmount { get; set; }

    public decimal? PickUpLongitude { get; set; }

    public decimal? PickUpLatitude { get; set; }

    public decimal? DeliveryLongitude { get; set; }

    public decimal? DeliveryLatitude { get; set; }

    public int? Dgclass { get; set; }

    public bool? Dgdocument { get; set; }

    public string UcbkClientRefc { get; set; }

    public decimal? Gssamount { get; set; }

    public decimal? RawAmount { get; set; }

    public string FromAddressExtras { get; set; }

    public string FromAddressStreetName { get; set; }

    public string FromAddressExtras2 { get; set; }

    public string ToAddressExtras { get; set; }

    public string ToAddressStreetName { get; set; }

    public string ToAddressExtras2 { get; set; }

    public string Gssconnote { get; set; }

    public double? Cubic { get; set; }

    public string GssTrackingUrl { get; set; }

    public decimal? PickupRawAmount { get; set; }

    public decimal? DropoffRawAmount { get; set; }

    public decimal? NwrawAmount { get; set; }

    public int? TrackingMethod { get; set; }

    public string TrackingMobile { get; set; }

    public string TrackingEmail { get; set; }

    public double? RunCourierPercentage { get; set; }

    public string RunName { get; set; }

    public int? FromGeoType { get; set; }

    public int? ToGeoType { get; set; }

    public double? UcbkKm { get; set; }

    public int? ShopId { get; set; }

    public string ShopRef1 { get; set; }

    public string ShopRef2 { get; set; }

    public string ShopRef3 { get; set; }

    public string ShopRef4 { get; set; }

    public string ShopRef5 { get; set; }

    public int? DepotId { get; set; }

    public string Barcode { get; set; }

    public int? StorageState { get; set; }

    public int? DeliveryState { get; set; }

    public int? SourceId { get; set; }

    public string StripeChargeId { get; set; }

    public string ScheduleName { get; set; }

    public int? LoggedInContactId { get; set; }

    public int? ScheduleId { get; set; }

    public int? DropOffLocationId { get; set; }

    public decimal? CourierPercentageOverride { get; set; }

    public string ClientItemIds { get; set; }

    public int? BulkParentId { get; set; }

    public bool? DocRequired { get; set; }

    public string PickupAddressLine1 { get; set; }

    public string PickupAddressLine2 { get; set; }

    public string PickupAddressLine3 { get; set; }

    public string PickupAddressLine4 { get; set; }

    public string PickupAddressLine5 { get; set; }

    public string PickupAddressLine6 { get; set; }

    public string PickupAddressLine7 { get; set; }

    public string PickupAddressLine8 { get; set; }

    public string DeliveryAddressLine1 { get; set; }

    public string DeliveryAddressLine2 { get; set; }

    public string DeliveryAddressLine3 { get; set; }

    public string DeliveryAddressLine4 { get; set; }

    public string DeliveryAddressLine5 { get; set; }

    public string DeliveryAddressLine6 { get; set; }

    public string DeliveryAddressLine7 { get; set; }

    public string DeliveryAddressLine8 { get; set; }

    public decimal? DryIceWeight { get; set; }

    public int? FromAirportId { get; set; }

    public int? ToAirportId { get; set; }

    public DateTime? DeliverByTime { get; set; }

    public decimal? CourierPayment { get; set; }

    public decimal? CourierFuel { get; set; }

    public int? PickupTimeZoneId { get; set; }

    public int UcbkDaysInt { get; set; }

    /// <summary>
    /// Frequency of job recurrence (Weekly=1, Fortnightly=2, FirstOfMonth=4, etc.)
    /// </summary>
    public int? UcbkFrequency { get; set; }

    /// <summary>
    /// 0 = Don&apos;t Book (default), 1 = Deliver Next Day
    /// </summary>
    public int HolidayDeliveryOption { get; set; }

    public decimal? TotalDistance { get; set; }

    public int? DeliverByTimeZoneId { get; set; }

    public int? PickUpWindowMins { get; set; }

    public int? DeliverByWindowMins { get; set; }

    public int? DimensionsType { get; set; }

    public string CustomJobName { get; set; }

    public string Connote { get; set; }

    public int? AccessorialChargeGroupId { get; set; }

    public DateTime? CreatedTime { get; set; }

    public int? RecurringInitialDays { get; set; }

    public DateTime? CreatedTimeUtc { get; set; }

    public decimal? FuelPercentage { get; set; }

    public decimal? PumpPrice { get; set; }

    public int? NpAgentId { get; set; }

    public virtual TucJobBooking BookingParent { get; set; }

    public virtual TucCourier Courier { get; set; }

    public virtual ICollection<TucJobBooking> InverseBookingParent { get; set; } = new List<TucJobBooking>();

    public virtual TucClientContact LoggedInContact { get; set; }

    public virtual ICollection<TucNote> TucNotes { get; set; } = new List<TucNote>();

    public virtual TucClient UcbkClient { get; set; }

    public virtual TucJobType UcbkSpeedNavigation { get; set; }
}
