// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoutedOperations.Core.Domain.Despatch;

public partial class TucJob
{
    public int UcjbId { get; set; }

    public string UcjbNumber { get; set; }

    public DateTime UcjbDate { get; set; }

    public DateTime? UcjbTime { get; set; }

    public double? UcjbType { get; set; }

    public int? UcjbClientId { get; set; }

    public string UcjbContact { get; set; }

    public double? UcjbChargeType { get; set; }

    public decimal? UcjbAmount { get; set; }

    public int? UcjbSpeed { get; set; }

    public int? UcjbFrom { get; set; }

    public string UcjbFromAddr { get; set; }

    public int? UcjbTo { get; set; }

    public string UcjbToSpecial { get; set; }

    public string UcjbToAddr { get; set; }

    public int? UcjbSize { get; set; }

    public short? UcjbQty { get; set; }

    public bool UcjbCbd { get; set; }

    public double? UcjbKm { get; set; }

    public string UcjbFlightDetails { get; set; }

    public double? UcjbWeight { get; set; }

    public int? UcjbStatus { get; set; }

    public DateTime? UcjbDispTime { get; set; }

    public DateTime? UcjbDispDate { get; set; }

    public int? UcjbCourierId { get; set; }

    public DateTime? UcjbComplTime { get; set; }

    public bool UcjbJobDone { get; set; }

    public string UcjbClientRefa { get; set; }

    public string UcjbClientRefb { get; set; }

    public string UcjbOurRef { get; set; }

    public int? UcjbOpId { get; set; }

    public int? UcjbDispId { get; set; }

    public bool UcjbVan { get; set; }

    public bool UcjbReturn { get; set; }

    public bool UcjbVoid { get; set; }

    public bool UcjbAttention { get; set; }

    public short? UcjbPickUpFrom { get; set; }

    public bool UcjbPaged { get; set; }

    public DateTime? UcjbPagedTime { get; set; }

    public string UcjbPodname { get; set; }

    public string UcjbClientCode { get; set; }

    public int? UcjbLatePick { get; set; }

    public int? UcjbLateDel { get; set; }

    public int? UcjbRefJobId { get; set; }

    public string UcjbNotes { get; set; }

    public bool UcjbMobileSend { get; set; }

    public DateTime? UcjbSendTime { get; set; }

    public string UcjbContactPhone { get; set; }

    public bool RemoteJob { get; set; }

    public int? NumRef1 { get; set; }

    public int? NumRef2 { get; set; }

    public int? NumRef3 { get; set; }

    public int? NumRef4 { get; set; }

    public string TextRef1 { get; set; }

    public string TextRef2 { get; set; }

    public string TextRef3 { get; set; }

    public string TextRef4 { get; set; }

    public bool SaturdayDelivery { get; set; }

    public DateTime? PickUpTime { get; set; }

    public decimal RebateAmt { get; set; }

    public decimal FuelSurchargeAmount { get; set; }

    public string ClientNotes { get; set; }

    public string InternalNotes { get; set; }

    public string PickupFromContact { get; set; }

    public string PickupFromPhone { get; set; }

    public int? DeliverToPrivateBusiness { get; set; }

    public string DeliverToContact { get; set; }

    public string DeliverToPhone { get; set; }

    public int? DeliverToLeaveId { get; set; }

    public int? ProofOfDelivery { get; set; }

    public string ProofOfDeliveryEmail { get; set; }

    public string ProofOfDeliveryMobile { get; set; }

    public int? ContactId { get; set; }

    public bool LatePickupNotificationHasBeenSent { get; set; }

    public DateTime? WhenLatePickupNotificationSent { get; set; }

    public bool LateDeliveryNotificationHasBeenSent { get; set; }

    public DateTime? WhenLateDeliveryNotificationSent { get; set; }

    public bool PodnotificationHasBeenSent { get; set; }

    public DateTime? WhenPodnotificationSent { get; set; }

    public bool RatedManually { get; set; }

    public bool RuralDelivery { get; set; }

    public byte[] PickUpSignature { get; set; }

    public byte[] DeliverySignature { get; set; }

    public decimal? PickUpLongitude { get; set; }

    public decimal? PickUpLatitude { get; set; }

    public decimal? DeliveryLongitude { get; set; }

    public decimal? DeliveryLatitude { get; set; }

    public int? WaitedPickUp { get; set; }

    public int? WaitedDelivery { get; set; }

    public string PickUpName { get; set; }

    public int? DesiredJobTypeId { get; set; }

    public int? AcceptedJobTypeId { get; set; }

    public bool Direct { get; set; }

    public int? NotifiedJobTypeId { get; set; }

    public int? UndeliverableLocationId { get; set; }

    public int? JobRelationshipTypeId { get; set; }

    public int? ParentId { get; set; }

    public int? InformationParentId { get; set; }

    public int? RootParentId { get; set; }

    public int? ClosestCourierId { get; set; }

    public bool? DisplayInDespatch { get; set; }

    public int? Sequence { get; set; }

    public bool ColsolidateMarsInformation { get; set; }

    public DateTime? WhenColsolidateMarsInformation { get; set; }

    public int? ClosestCourierRule { get; set; }

    public bool? SpeedChangeNotificationHasBeenSent { get; set; }

    public DateTime? WhenSpeedChangeNotificationSent { get; set; }

    public bool? AutoDespatch { get; set; }

    public byte? PickRunOrder { get; set; }

    public byte? DropRunOrder { get; set; }

    public decimal? Ppdamount { get; set; }

    public decimal? PpdexclusiveAmount { get; set; }

    public decimal? Gstrate { get; set; }

    public bool? Truck { get; set; }

    public DateTime? TruckStartTime { get; set; }

    public double? TruckHours { get; set; }

    public DateTime? RequiredDeliveryTime { get; set; }

    public int? InternalStatus { get; set; }

    public DateTime? FollowupTime { get; set; }

    public bool? Reprice { get; set; }

    public decimal? PickupAmount { get; set; }

    public decimal? DropoffAmount { get; set; }

    public bool? BulletFreight { get; set; }

    public decimal? Nwamount { get; set; }

    public bool? VanOk { get; set; }

    public int? Dgclass { get; set; }

    public bool? Dgdocument { get; set; }

    public bool ItemNotReadyNotificationHasBeenSent { get; set; }

    public bool ItemNotReadyNotification { get; set; }

    public DateTime? WhenItemNotReadyNotificationSent { get; set; }

    public string ItemNotReadyNotificationNotes { get; set; }

    public bool? EmailForJobFu { get; set; }

    public string UcjbClientRefc { get; set; }

    public decimal? Gssamount { get; set; }

    public decimal? RawAmount { get; set; }

    public string FromAddressExtras { get; set; }

    public string FromAddressStreetName { get; set; }

    public string FromAddressExtras2 { get; set; }

    public string ToAddressExtras { get; set; }

    public string ToAddressStreetName { get; set; }

    public string ToAddressExtras2 { get; set; }

    public string Gssconnote { get; set; }

    public double? Cubic { get; set; }

    public string GssTrackingUrl { get; set; }

    public decimal? PickupRawAmount { get; set; }

    public decimal? DropoffRawAmount { get; set; }

    public decimal? NwrawAmount { get; set; }

    public int? FdcourierId { get; set; }

    public bool DesCheck { get; set; }

    public bool JobTrackingNotificationHasBeenSent { get; set; }

    public DateTime? WhenJobTrackingNotificationSent { get; set; }

    public int? TrackingMethod { get; set; }

    public string TrackingMobile { get; set; }

    public string TrackingEmail { get; set; }

    public bool FirstJob { get; set; }

    public double? RunCourierPercentage { get; set; }

    public string RunName { get; set; }

    public int? FromGeoType { get; set; }

    public int? ToGeoType { get; set; }

    public int? Duration { get; set; }

    public byte[] DeliveryPhoto { get; set; }

    public string DeliveryGps { get; set; }

    public decimal? CourierPayment { get; set; }

    public decimal? RawBaseAmount { get; set; }

    public decimal? CourierBonus { get; set; }

    public int? ShopId { get; set; }

    public string ShopRef1 { get; set; }

    public string ShopRef2 { get; set; }

    public string ShopRef3 { get; set; }

    public string ShopRef4 { get; set; }

    public string ShopRef5 { get; set; }

    public DateTime? OutForDelivery { get; set; }

    public int? DepotId { get; set; }

    public string Barcode { get; set; }

    public int? StorageState { get; set; }

    public int? DeliveryState { get; set; }

    public int? SourceId { get; set; }

    public string StripeChargeId { get; set; }

    public bool? UcjbLocked { get; set; }

    public string ScheduleName { get; set; }

    public int? LoggedInContactId { get; set; }

    public decimal? CourierFuel { get; set; }

    public decimal? CourierPercentage { get; set; }

    public int? DropOffLocationId { get; set; }

    public decimal? CourierPercentageOverride { get; set; }

    public string ClientItemIds { get; set; }

    public int? BulkParentId { get; set; }

    public bool? DocRequired { get; set; }

    public string PickupAddressLine1 { get; set; }

    public string PickupAddressLine2 { get; set; }

    public string PickupAddressLine3 { get; set; }

    public string PickupAddressLine4 { get; set; }

    public string PickupAddressLine5 { get; set; }

    public string PickupAddressLine6 { get; set; }

    public string PickupAddressLine7 { get; set; }

    public string PickupAddressLine8 { get; set; }

    public string DeliveryAddressLine1 { get; set; }

    public string DeliveryAddressLine2 { get; set; }

    public string DeliveryAddressLine3 { get; set; }

    public string DeliveryAddressLine4 { get; set; }

    public string DeliveryAddressLine5 { get; set; }

    public string DeliveryAddressLine6 { get; set; }

    public string DeliveryAddressLine7 { get; set; }

    public string DeliveryAddressLine8 { get; set; }

    public int? FromAirportId { get; set; }

    public int? ToAirportId { get; set; }

    public decimal? DryIceWeight { get; set; }

    public DateTime? DeliverByTime { get; set; }

    public int? AgentId { get; set; }

    public string Connote { get; set; }

    public int? PickupTimeZoneId { get; set; }

    public decimal? TotalDistance { get; set; }

    public int? DeliverByTimeZoneId { get; set; }

    public int? PickUpWindowMins { get; set; }

    public int? DeliverByWindowMins { get; set; }

    public int? MasterCourierId { get; set; }

    public decimal? SubContractorBonusPercentage { get; set; }

    public decimal? SubContractorFuelPercentage { get; set; }

    public decimal? SubContractorPercentage { get; set; }

    public bool? IsRecurringJob { get; set; }

    public int? BookingParentId { get; set; }

    public string PickupGps { get; set; }

    public string PickupCondition { get; set; }

    public int? DimensionsType { get; set; }

    public string CustomJobName { get; set; }

    public int? ManualArchiveAttempts { get; set; }

    public int? AccessorialChargeGroupId { get; set; }

    public DateTime? CreatedTime { get; set; }

    public DateTime? PickupArrivalTime { get; set; }

    public DateTime? DeliveryArrivalTime { get; set; }

    public bool? CourierPaymentManualOverride { get; set; }

    public DateTime? CreatedTimeUtc { get; set; }

    public decimal? ClosestCourierConfidence { get; set; }

    public DateTime? ClosestCourierScoredAt { get; set; }

    public Guid? PartnerJobGuid { get; set; }

    public decimal? PartnerAgreedRate { get; set; }

    public int? PartnerPairingId { get; set; }

    public int? ScheduleId { get; set; }

    public decimal? FuelPercentage { get; set; }

    public decimal? PumpPrice { get; set; }

    public int? NpAgentId { get; set; }

    public decimal? NpCourierPayment { get; set; }

    public virtual TucJobType AcceptedJobType { get; set; }

    public virtual TucClientContact Contact { get; set; }

    public virtual TucJobType DesiredJobType { get; set; }

    public virtual TucCourier Fdcourier { get; set; }

    public virtual ICollection<JobDeliveryJourney> JobDeliveryJourneys { get; set; } = new List<JobDeliveryJourney>();

    public virtual TucCourier MasterCourier { get; set; }

    public virtual TucJobType NotifiedJobType { get; set; }

    public virtual ICollection<TucNote> TucNotes { get; set; } = new List<TucNote>();

    public virtual TucClient UcjbClient { get; set; }

    public virtual TucCourier UcjbCourier { get; set; }

    public virtual TucSuburb UcjbFromNavigation { get; set; }

    public virtual TucJobType UcjbSpeedNavigation { get; set; }

    public virtual TucJobStatus UcjbStatusNavigation { get; set; }

    public virtual TucSuburb UcjbToNavigation { get; set; }
}
