// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoutedOperations.Core.Domain.Despatch;

public partial class TucJobStatus
{
    public int UcjsId { get; set; }

    public string UcjsReplyCode { get; set; }

    public string UcjsName { get; set; }

    public string UcjsCode { get; set; }

    public int? JobStatusNotificationId { get; set; }

    public virtual ICollection<JobDeliveryJourney> JobDeliveryJourneyNewJobStatuses { get; set; } = new List<JobDeliveryJourney>();

    public virtual ICollection<JobDeliveryJourney> JobDeliveryJourneyOldJobStatuses { get; set; } = new List<JobDeliveryJourney>();

    public virtual ICollection<TblBulkJob> TblBulkJobs { get; set; } = new List<TblBulkJob>();

    public virtual ICollection<TucJob> TucJobs { get; set; } = new List<TucJob>();
}
