// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoutedOperations.Core.Domain.Despatch;

public partial class TucNote
{
    public int NoteId { get; set; }

    public int NoteTypeId { get; set; }

    public int? JobId { get; set; }

    public int? JobBookingId { get; set; }

    public string NoteText { get; set; }

    public bool IsImportant { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? ProcessedNotificationDate { get; set; }

    public int? NpAgentId { get; set; }

    public virtual TucJob Job { get; set; }

    public virtual TucJobBooking JobBooking { get; set; }

    public virtual TucNoteType NoteType { get; set; }
}
