// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RoutedOperations.Core.Domain.Despatch;

public partial class TucNoteType
{
    public int NoteTypeId { get; set; }

    public string NoteTypeName { get; set; }

    public bool IsPublic { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public bool IsSystemDefined { get; set; }

    public virtual ICollection<TblBulkJobNote> TblBulkJobNotes { get; set; } = new List<TblBulkJobNote>();

    public virtual ICollection<TucNote> TucNotes { get; set; } = new List<TucNote>();
}
