//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCLRun
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DespatchContext : DbContext
    {
        public DespatchContext()
            : base("name=DespatchContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBulkJob> tblBulkJobs { get; set; }
    
        public virtual ObjectResult<PotentialCouriers> GetPotentialCouriers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PotentialCouriers>("GetPotentialCouriers");
        }
    
        public virtual ObjectResult<BulkJob> GetBulkJobs(Nullable<System.DateTime> dateTime, Nullable<int> clientID)
        {
            var dateTimeParameter = dateTime.HasValue ?
                new ObjectParameter("DateTime", dateTime) :
                new ObjectParameter("DateTime", typeof(System.DateTime));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BulkJob>("GetBulkJobs", dateTimeParameter, clientIDParameter);
        }
    
        public virtual int InsertJob(Nullable<int> bulkJobID, Nullable<int> courierID, string runName, Nullable<int> runOrder, Nullable<double> courierPercentage)
        {
            var bulkJobIDParameter = bulkJobID.HasValue ?
                new ObjectParameter("BulkJobID", bulkJobID) :
                new ObjectParameter("BulkJobID", typeof(int));
    
            var courierIDParameter = courierID.HasValue ?
                new ObjectParameter("CourierID", courierID) :
                new ObjectParameter("CourierID", typeof(int));
    
            var runNameParameter = runName != null ?
                new ObjectParameter("RunName", runName) :
                new ObjectParameter("RunName", typeof(string));
    
            var runOrderParameter = runOrder.HasValue ?
                new ObjectParameter("RunOrder", runOrder) :
                new ObjectParameter("RunOrder", typeof(int));
    
            var courierPercentageParameter = courierPercentage.HasValue ?
                new ObjectParameter("CourierPercentage", courierPercentage) :
                new ObjectParameter("CourierPercentage", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertJob", bulkJobIDParameter, courierIDParameter, runNameParameter, runOrderParameter, courierPercentageParameter);
        }
    
        public virtual int InsertOrUpdateJobRun(Nullable<int> runID, Nullable<int> bulkJobID, Nullable<int> runOrder)
        {
            var runIDParameter = runID.HasValue ?
                new ObjectParameter("RunID", runID) :
                new ObjectParameter("RunID", typeof(int));
    
            var bulkJobIDParameter = bulkJobID.HasValue ?
                new ObjectParameter("BulkJobID", bulkJobID) :
                new ObjectParameter("BulkJobID", typeof(int));
    
            var runOrderParameter = runOrder.HasValue ?
                new ObjectParameter("RunOrder", runOrder) :
                new ObjectParameter("RunOrder", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertOrUpdateJobRun", runIDParameter, bulkJobIDParameter, runOrderParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> InsertOrUpdateRun(Nullable<int> runID, string name, Nullable<int> mins, Nullable<double> kms, Nullable<int> courierID, Nullable<int> status, Nullable<decimal> revenue, Nullable<decimal> payout, Nullable<double> courierPercentage, string googleRouteResponse)
        {
            var runIDParameter = runID.HasValue ?
                new ObjectParameter("RunID", runID) :
                new ObjectParameter("RunID", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var minsParameter = mins.HasValue ?
                new ObjectParameter("Mins", mins) :
                new ObjectParameter("Mins", typeof(int));
    
            var kmsParameter = kms.HasValue ?
                new ObjectParameter("Kms", kms) :
                new ObjectParameter("Kms", typeof(double));
    
            var courierIDParameter = courierID.HasValue ?
                new ObjectParameter("CourierID", courierID) :
                new ObjectParameter("CourierID", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            var revenueParameter = revenue.HasValue ?
                new ObjectParameter("Revenue", revenue) :
                new ObjectParameter("Revenue", typeof(decimal));
    
            var payoutParameter = payout.HasValue ?
                new ObjectParameter("Payout", payout) :
                new ObjectParameter("Payout", typeof(decimal));
    
            var courierPercentageParameter = courierPercentage.HasValue ?
                new ObjectParameter("CourierPercentage", courierPercentage) :
                new ObjectParameter("CourierPercentage", typeof(double));
    
            var googleRouteResponseParameter = googleRouteResponse != null ?
                new ObjectParameter("GoogleRouteResponse", googleRouteResponse) :
                new ObjectParameter("GoogleRouteResponse", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("InsertOrUpdateRun", runIDParameter, nameParameter, minsParameter, kmsParameter, courierIDParameter, statusParameter, revenueParameter, payoutParameter, courierPercentageParameter, googleRouteResponseParameter);
        }
    
        public virtual ObjectResult<BulkRun> GetBulkRun(Nullable<System.DateTime> dateTime, Nullable<int> clientID)
        {
            var dateTimeParameter = dateTime.HasValue ?
                new ObjectParameter("DateTime", dateTime) :
                new ObjectParameter("DateTime", typeof(System.DateTime));
    
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BulkRun>("GetBulkRun", dateTimeParameter, clientIDParameter);
        }
    
        public virtual int DeleteBulkRun(Nullable<int> runID)
        {
            var runIDParameter = runID.HasValue ?
                new ObjectParameter("RunID", runID) :
                new ObjectParameter("RunID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteBulkRun", runIDParameter);
        }
    
        public virtual ObjectResult<BulkRunSetting> GetBulkRunSettings()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BulkRunSetting>("GetBulkRunSettings");
        }
    }
}
