import type { ImportSchema } from '../types';

export const clientsSchema: ImportSchema = {
  id: 'clients',
  label: 'Clients & Customers',
  description: 'Import/export client account data',
  columns: [
    {
      key: 'id',
      header: 'Client ID',
      type: 'id',
      locked: true,
      templateHint: '[AUTO - DO NOT EDIT]',
    },
    {
      key: 'name',
      header: 'Company Name',
      type: 'string',
      required: true,
      templateHint: 'Required - Company legal name',
    },
    {
      key: 'code',
      header: 'Client Code',
      type: 'string',
      pattern: /^[A-Z0-9-]+$/,
      templateHint: 'Alphanumeric code (e.g., ABC-123)',
    },
    {
      key: 'status',
      header: 'Status',
      type: 'enum',
      values: ['Active', 'Inactive'],
      templateDefault: 'Active',
      templateHint: 'Active/Inactive',
    },
    {
      key: 'type',
      header: 'Client Type',
      type: 'enum',
      values: ['Corporate', 'Individual', 'Partner'],
      templateDefault: 'Corporate',
      templateHint: 'Corporate/Individual/Partner',
    },
    {
      key: 'address',
      header: 'Street Address',
      type: 'string',
      templateHint: '123 Main Street',
    },
    {
      key: 'city',
      header: 'City',
      type: 'string',
      templateHint: 'City name',
    },
    {
      key: 'state',
      header: 'State/Province',
      type: 'string',
      templateHint: 'State or province',
    },
    {
      key: 'zip',
      header: 'Postal Code',
      type: 'string',
      templateHint: 'ZIP or postal code',
    },
    {
      key: 'country',
      header: 'Country',
      type: 'string',
      templateHint: 'Country name',
    },
    {
      key: 'phone',
      header: 'Phone',
      type: 'phone',
      templateHint: '+1 555-123-4567',
    },
    {
      key: 'email',
      header: 'Email',
      type: 'email',
      templateHint: 'email@example.com',
    },
    {
      key: 'website',
      header: 'Website',
      type: 'string',
      templateHint: 'https://www.example.com',
    },
    {
      key: 'billingType',
      header: 'Billing Type',
      type: 'enum',
      values: ['Monthly Invoice', 'Weekly Invoice', 'Per Job', 'COD'],
      templateDefault: 'Monthly Invoice',
      templateHint: 'Monthly Invoice/Weekly Invoice/Per Job/COD',
    },
    {
      key: 'paymentTerms',
      header: 'Payment Terms',
      type: 'enum',
      values: ['Net 7', 'Net 15', 'Net 30', 'Net 60', 'COD'],
      templateDefault: 'Net 30',
      templateHint: 'Net 7/Net 15/Net 30/Net 60/COD',
    },
    {
      key: 'creditLimit',
      header: 'Credit Limit',
      type: 'number',
      min: 0,
      templateHint: 'Credit limit amount (minimum: 0)',
    },
    {
      key: 'taxId',
      header: 'Tax ID/ABN',
      type: 'string',
      templateHint: 'Tax identification number',
    },
    {
      key: 'notes',
      header: 'Notes',
      type: 'string',
      templateHint: 'Additional notes or comments',
    },
    {
      key: 'rateGroupId',
      header: 'Rate Group',
      type: 'reference',
      refTable: 'rateGroups',
      templateHint: 'Reference to rateGroups',
    },
    {
      key: 'agentId',
      header: 'Assigned Agent',
      type: 'reference',
      refTable: 'agents',
      templateHint: 'Reference to agents',
    },
    {
      key: 'createdAt',
      header: 'Created Date',
      type: 'datetime',
      locked: true,
      templateHint: '[AUTO - DO NOT EDIT]',
    },
    {
      key: 'updatedAt',
      header: 'Updated Date',
      type: 'datetime',
      locked: true,
      templateHint: '[AUTO - DO NOT EDIT]',
    },
  ],
  uniqueKey: 'id',
  generateId: () => `CL-${Date.now().toString(36).toUpperCase()}`,
};
