import type { ImportSchema } from '../types';

export const schedulesSchema: ImportSchema = {
  id: 'schedules',
  label: 'Schedules',
  description: 'Import/export delivery schedule configurations',
  columns: [
    {
      key: 'id',
      header: 'Schedule ID',
      type: 'id',
      locked: true,
      templateHint: '[AUTO - DO NOT EDIT]',
    },
    {
      key: 'name',
      header: 'Schedule Name',
      type: 'string',
      required: true,
      templateHint: 'Required - Descriptive name for the schedule',
    },
    {
      key: 'isActive',
      header: 'Active',
      type: 'boolean',
      templateDefault: 'true',
      templateHint: 'true/false',
    },
    {
      key: 'isOverride',
      header: 'Is Override',
      type: 'boolean',
      templateDefault: 'false',
      templateHint: 'true/false - Is this a client override?',
    },
    {
      key: 'baseScheduleId',
      header: 'Base Schedule ID',
      type: 'reference',
      refTable: 'schedules',
      templateHint: 'If override, reference to base schedule',
    },
    {
      key: 'originType',
      header: 'Origin Type',
      type: 'enum',
      values: ['depot', 'client_address', 'airport'],
      templateDefault: 'depot',
      templateHint: 'depot/client_address/airport',
    },
    {
      key: 'originDepotId',
      header: 'Origin Depot',
      type: 'reference',
      refTable: 'depots',
      templateHint: 'Reference to depots table',
    },
    {
      key: 'bookingMode',
      header: 'Booking Mode',
      type: 'enum',
      values: ['instant', 'scheduled_same_day', 'scheduled_advance'],
      templateDefault: 'instant',
      templateHint: 'instant/scheduled_same_day/scheduled_advance',
    },
    {
      key: 'clientVisibility',
      header: 'Client Visibility',
      type: 'enum',
      values: ['all', 'specific'],
      templateDefault: 'all',
      templateHint: 'all/specific',
    },
    {
      key: 'clientIds',
      header: 'Client IDs',
      type: 'string',
      templateHint: 'Comma-separated client IDs if visibility is specific',
    },
    {
      key: 'defaultCollectionSpeedId',
      header: 'Default Collection Speed',
      type: 'reference',
      refTable: 'speeds',
      templateHint: 'Reference to speeds table',
    },
    {
      key: 'defaultDeliverySpeedId',
      header: 'Default Delivery Speed',
      type: 'reference',
      refTable: 'speeds',
      templateHint: 'Reference to speeds table',
    },
    {
      key: 'operatingDays',
      header: 'Operating Days',
      type: 'string',
      templateHint: 'Comma-separated: Mon,Tue,Wed,Thu,Fri,Sat,Sun',
    },
    {
      key: 'cutoffValue',
      header: 'Cutoff Value',
      type: 'number',
      templateHint: 'Numeric cutoff value',
    },
    {
      key: 'cutoffUnit',
      header: 'Cutoff Unit',
      type: 'enum',
      values: ['minutes', 'hours', 'days'],
      templateDefault: 'hours',
      templateHint: 'minutes/hours/days',
    },
    {
      key: 'createdAt',
      header: 'Created Date',
      type: 'datetime',
      locked: true,
      templateHint: '[AUTO - DO NOT EDIT]',
    },
    {
      key: 'updatedAt',
      header: 'Updated Date',
      type: 'datetime',
      locked: true,
      templateHint: '[AUTO - DO NOT EDIT]',
    },
  ],
  uniqueKey: 'id',
  generateId: () => `SCH-${Date.now().toString(36).toUpperCase()}`,
};
