// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace RunBuilder.Models;

public partial class DespatchContext : DbContext
{
    public DespatchContext(DbContextOptions<DespatchContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TblBulkJob> TblBulkJobs { get; set; }

    public virtual DbSet<TblBulkJobRun> TblBulkJobRuns { get; set; }

    public virtual DbSet<TblBulkRun> TblBulkRuns { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("SQL_Latin1_General_CP1_CI_AS");

        modelBuilder.Entity<TblBulkJob>(entity =>
        {
            entity.HasKey(e => e.BulkJobId).HasName("PK__tblBulkJ__1B2363F00EF20DB6");

            entity.ToTable("tblBulkJob", tb =>
                {
                    tb.HasTrigger("tblBulkJob_Insert");
                    tb.HasTrigger("tblBulkJob_Update");
                });

            entity.HasIndex(e => e.BookDate, "BookDate-NonClusteredIndex-20190824-120700");

            entity.HasIndex(e => e.BookDate, "DespatchWebSearch2");

            entity.HasIndex(e => e.ImportId, "FK_ImportId").IsDescending();

            entity.HasIndex(e => new { e.ShopId, e.ShopRef1, e.ShopRef2, e.ShopRef3, e.ShopRef4, e.ShopRef5 }, "IX_Shop");

            entity.HasIndex(e => e.JobId, "JobId-NonClusteredIndex-20190417-112100").IsDescending();

            entity.HasIndex(e => e.BookDate, "idx_BookDate");

            entity.HasIndex(e => new { e.Done, e.JobId, e.Void, e.BookDate }, "idx_tblBulkJob_Done_JobID_Void_BookDate");

            entity.Property(e => e.BulkJobId).HasColumnName("BulkJobID");
            entity.Property(e => e.Amount).HasColumnType("money");
            entity.Property(e => e.Barcode).HasMaxLength(300);
            entity.Property(e => e.BookDate).HasColumnType("datetime");
            entity.Property(e => e.BookTime).HasColumnType("datetime");
            entity.Property(e => e.BulkParentId).HasColumnName("BulkParentID");
            entity.Property(e => e.BulkRunId).HasColumnName("BulkRunID");
            entity.Property(e => e.ClientCode).HasMaxLength(5);
            entity.Property(e => e.ClientId).HasColumnName("ClientID");
            entity.Property(e => e.ClientItemIds).HasMaxLength(100);
            entity.Property(e => e.ClientRefa).HasMaxLength(20);
            entity.Property(e => e.ClientRefb).HasMaxLength(15);
            entity.Property(e => e.Contact).HasMaxLength(50);
            entity.Property(e => e.CourierId).HasColumnName("CourierID");
            entity.Property(e => e.CourierPayment).HasColumnType("money");
            entity.Property(e => e.CourierPercentageOverride).HasColumnType("numeric(5, 4)");
            entity.Property(e => e.DeliverToContact).HasMaxLength(100);
            entity.Property(e => e.DeliverToLeaveId).HasColumnName("DeliverToLeaveID");
            entity.Property(e => e.DeliverToPhone).HasMaxLength(100);
            entity.Property(e => e.DeliveryLatitude).HasMaxLength(50);
            entity.Property(e => e.DeliveryLongitude).HasMaxLength(50);
            entity.Property(e => e.DropOffLocationId).HasColumnName("DropOffLocationID");
            entity.Property(e => e.FromAddress).HasMaxLength(150);
            entity.Property(e => e.FromCompany).HasMaxLength(150);
            entity.Property(e => e.FromSuburb).HasMaxLength(50);
            entity.Property(e => e.Height).HasColumnType("numeric(18, 0)");
            entity.Property(e => e.InformationParentId).HasColumnName("InformationParentID");
            entity.Property(e => e.JobId).HasColumnName("JobID");
            entity.Property(e => e.JobNumber)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.JobRelationshipTypeId).HasColumnName("JobRelationshipTypeID");
            entity.Property(e => e.Length).HasColumnType("numeric(18, 0)");
            entity.Property(e => e.LinehaulRunId).HasColumnName("LinehaulRunID");
            entity.Property(e => e.LoggedInContactId).HasColumnName("LoggedInContactID");
            entity.Property(e => e.Manifest).HasMaxLength(50);
            entity.Property(e => e.MultiboxParentId).HasColumnName("MultiboxParentID");
            entity.Property(e => e.Notes).HasMaxLength(4000);
            entity.Property(e => e.NwdocJob).HasColumnName("NWDocJob");
            entity.Property(e => e.OrderRef).HasMaxLength(50);
            entity.Property(e => e.OurRef).HasMaxLength(20);
            entity.Property(e => e.ParentId).HasColumnName("ParentID");
            entity.Property(e => e.PickUpLatitude).HasMaxLength(50);
            entity.Property(e => e.PickUpLongitude).HasMaxLength(50);
            entity.Property(e => e.PickupReadyDateTime).HasColumnType("datetime");
            entity.Property(e => e.ProofOfDeliveryEmail).HasMaxLength(500);
            entity.Property(e => e.ProofOfDeliveryMobile).HasMaxLength(100);
            entity.Property(e => e.RegionId).HasColumnName("RegionID");
            entity.Property(e => e.RootParentId).HasColumnName("RootParentID");
            entity.Property(e => e.RunName).HasMaxLength(50);
            entity.Property(e => e.ScheduleId).HasColumnName("ScheduleID");
            entity.Property(e => e.ScheduleName).HasMaxLength(200);
            entity.Property(e => e.ShopRef1).HasMaxLength(50);
            entity.Property(e => e.ShopRef2).HasMaxLength(50);
            entity.Property(e => e.ShopRef3).HasMaxLength(50);
            entity.Property(e => e.ShopRef4).HasMaxLength(50);
            entity.Property(e => e.ShopRef5).HasMaxLength(50);
            entity.Property(e => e.SourceId).HasColumnName("SourceID");
            entity.Property(e => e.StripeChargeId)
                .HasMaxLength(50)
                .HasColumnName("StripeChargeID");
            entity.Property(e => e.ToAddress).HasMaxLength(150);
            entity.Property(e => e.ToCompany).HasMaxLength(150);
            entity.Property(e => e.ToSuburb).HasMaxLength(50);
            entity.Property(e => e.TrackingEmail).HasMaxLength(500);
            entity.Property(e => e.TrackingMobile).HasMaxLength(500);
            entity.Property(e => e.Weight).HasColumnType("decimal(6, 2)");
            entity.Property(e => e.Width).HasColumnType("numeric(18, 0)");
        });

        modelBuilder.Entity<TblBulkJobRun>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tblBulkJ__3214EC273DACFC9F");

            entity.ToTable("tblBulkJobRun");

            entity.HasIndex(e => e.RunId, "RunID-NonClusteredIndex-20190824-171500");

            entity.HasIndex(e => new { e.BulkJobId, e.RunId }, "idx_tblBulkJobRun_BulkJobID_RunID");

            entity.HasIndex(e => e.BulkJobId, "index_BulkJobID");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.BulkJobId).HasColumnName("BulkJobID");
            entity.Property(e => e.RunId).HasColumnName("RunID");

            entity.HasOne(d => d.BulkJob).WithMany(p => p.TblBulkJobRuns)
                .HasForeignKey(d => d.BulkJobId)
                .HasConstraintName("FK__tblBulkJo__BulkJ__4089694A");

            entity.HasOne(d => d.Run).WithMany(p => p.TblBulkJobRuns)
                .HasForeignKey(d => d.RunId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__tblBulkJo__RunID__3F954511");
        });

        modelBuilder.Entity<TblBulkRun>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tblBulkR__3214EC2736FFFF10");

            entity.ToTable("tblBulkRun");

            entity.HasIndex(e => new { e.Id, e.DespatchDateTime }, "idx_tblBulkRun_ID");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CourierId).HasColumnName("CourierID");
            entity.Property(e => e.Created)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DespatchDateTime).HasColumnType("datetime");
            entity.Property(e => e.LastModified)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Name).HasMaxLength(50);
            entity.Property(e => e.Payout).HasColumnType("money");
            entity.Property(e => e.Revenue).HasColumnType("money");
            entity.Property(e => e.Status).HasDefaultValue(0);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}