// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using RunBuilder.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace RunBuilder.Models
{
    public partial class DespatchContext
    {
        private IDespatchContextProcedures _procedures;

        public virtual IDespatchContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new DespatchContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IDespatchContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<UTL_stpCourier_ActiveResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<UTL_stpJob_tblBulkJobResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<UTL_stpJob_tblBulkRunResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<UTL_stpJob_tblBulkRun_InsertOrUpdateResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<UTL_stpJob_tblBulkRunSettingsResult>().HasNoKey().ToView(null);
        }
    }

    public partial class DespatchContextProcedures : IDespatchContextProcedures
    {
        private readonly DespatchContext _context;

        public DespatchContextProcedures(DespatchContext context)
        {
            _context = context;
        }

        public virtual async Task<List<UTL_stpCourier_ActiveResult>> UTL_stpCourier_ActiveAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<UTL_stpCourier_ActiveResult>("EXEC @returnValue = [dbo].[UTL_stpCourier_Active]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> UTL_stpJob_InsertFromRunBuilderAsync(int? BulkJobID, int? CourierID, string RunName, int? RunOrder, double? CourierPercentage, int? RunStatus, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "BulkJobID",
                    Value = BulkJobID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "CourierID",
                    Value = CourierID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "RunName",
                    Size = 100,
                    Value = RunName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "RunOrder",
                    Value = RunOrder ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "CourierPercentage",
                    Value = CourierPercentage ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "RunStatus",
                    Value = RunStatus ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[UTL_stpJob_InsertFromRunBuilder] @BulkJobID, @CourierID, @RunName, @RunOrder, @CourierPercentage, @RunStatus", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<UTL_stpJob_tblBulkJobResult>> UTL_stpJob_tblBulkJobAsync(DateTime? DateTime, int? ClientID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "DateTime",
                    Value = DateTime ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                new SqlParameter
                {
                    ParameterName = "ClientID",
                    Value = ClientID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<UTL_stpJob_tblBulkJobResult>("EXEC @returnValue = [dbo].[UTL_stpJob_tblBulkJob] @DateTime, @ClientID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> UTL_stpJob_tblBulkJobRun_InsertOrUpdateAsync(int? RunID, int? BulkJobID, int? RunOrder, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "RunID",
                    Value = RunID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "BulkJobID",
                    Value = BulkJobID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "RunOrder",
                    Value = RunOrder ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[UTL_stpJob_tblBulkJobRun_InsertOrUpdate] @RunID, @BulkJobID, @RunOrder", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<UTL_stpJob_tblBulkRunResult>> UTL_stpJob_tblBulkRunAsync(DateTime? DateTime, int? ClientID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "DateTime",
                    Value = DateTime ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                new SqlParameter
                {
                    ParameterName = "ClientID",
                    Value = ClientID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<UTL_stpJob_tblBulkRunResult>("EXEC @returnValue = [dbo].[UTL_stpJob_tblBulkRun] @DateTime, @ClientID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> UTL_stpJob_tblBulkRun_DeleteAsync(int? RunID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "RunID",
                    Value = RunID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[UTL_stpJob_tblBulkRun_Delete] @RunID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<UTL_stpJob_tblBulkRun_InsertOrUpdateResult>> UTL_stpJob_tblBulkRun_InsertOrUpdateAsync(int? RunID, string Name, int? Mins, double? Kms, int? CourierID, int? Status, decimal? Revenue, decimal? Payout, double? CourierPercentage, string GoogleRouteResponse, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "RunID",
                    Value = RunID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Name",
                    Size = 100,
                    Value = Name ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Mins",
                    Value = Mins ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Kms",
                    Value = Kms ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "CourierID",
                    Value = CourierID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Status",
                    Value = Status ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Revenue",
                    Precision = 19,
                    Scale = 4,
                    Value = Revenue ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Money,
                },
                new SqlParameter
                {
                    ParameterName = "Payout",
                    Precision = 19,
                    Scale = 4,
                    Value = Payout ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Money,
                },
                new SqlParameter
                {
                    ParameterName = "CourierPercentage",
                    Value = CourierPercentage ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "GoogleRouteResponse",
                    Size = -1,
                    Value = GoogleRouteResponse ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<UTL_stpJob_tblBulkRun_InsertOrUpdateResult>("EXEC @returnValue = [dbo].[UTL_stpJob_tblBulkRun_InsertOrUpdate] @RunID, @Name, @Mins, @Kms, @CourierID, @Status, @Revenue, @Payout, @CourierPercentage, @GoogleRouteResponse", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<UTL_stpJob_tblBulkRunSettingsResult>> UTL_stpJob_tblBulkRunSettingsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<UTL_stpJob_tblBulkRunSettingsResult>("EXEC @returnValue = [dbo].[UTL_stpJob_tblBulkRunSettings]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
