// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace RunBuilder.Models;

public partial class DespatchContext : DbContext
{
    public DespatchContext(DbContextOptions<DespatchContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TblBulkJob> TblBulkJobs { get; set; }

    public virtual DbSet<TblBulkJobRun> TblBulkJobRuns { get; set; }

    public virtual DbSet<TblBulkRun> TblBulkRuns { get; set; }

    public virtual DbSet<ZipPolygon> ZipPolygons { get; set; }

    public virtual DbSet<ZoneCombo> ZoneCombos { get; set; }

    public virtual DbSet<ZoneGroup> ZoneGroups { get; set; }

    public virtual DbSet<ZoneName> ZoneNames { get; set; }

    public virtual DbSet<ZoneZip> ZoneZips { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TblBulkJob>(entity =>
        {
            entity.HasKey(e => e.BulkJobId).HasName("PK__tblBulkJ__1B2363F0324172E1");

            entity.ToTable("tblBulkJob", tb =>
                {
                    tb.HasTrigger("tblBulkJob_Insert");
                    tb.HasTrigger("tblBulkJob_Update");
                });

            entity.HasIndex(e => e.BookDate, "BookDate-NonClusteredIndex-20190824-120700");

            entity.HasIndex(e => e.BookDate, "DespatchWebSearch2");

            entity.HasIndex(e => e.ImportId, "FK_ImportId").IsDescending();

            entity.HasIndex(e => new { e.ShopId, e.ShopRef1, e.ShopRef2, e.ShopRef3, e.ShopRef4, e.ShopRef5 }, "IX_Shop");

            entity.HasIndex(e => new { e.BulkJobId, e.ParentId, e.MultiboxParentId, e.BulkParentId }, "IX_tblBulkJob_Composite");

            entity.HasIndex(e => e.JobId, "IX_tblBulkJob_JobID");

            entity.HasIndex(e => e.JobId, "JobId-NonClusteredIndex-20190417-112100").IsDescending();

            entity.HasIndex(e => e.BookDate, "idx_BookDate");

            entity.Property(e => e.BulkJobId).HasColumnName("BulkJobID");
            entity.Property(e => e.Amount).HasColumnType("money");
            entity.Property(e => e.Barcode).HasMaxLength(300);
            entity.Property(e => e.BookDate).HasColumnType("datetime");
            entity.Property(e => e.BookTime).HasColumnType("datetime");
            entity.Property(e => e.BulkParentId).HasColumnName("BulkParentID");
            entity.Property(e => e.BulkRunId).HasColumnName("BulkRunID");
            entity.Property(e => e.ClientCode).HasMaxLength(5);
            entity.Property(e => e.ClientId).HasColumnName("ClientID");
            entity.Property(e => e.ClientItemIds).HasMaxLength(100);
            entity.Property(e => e.ClientRefa).HasMaxLength(20);
            entity.Property(e => e.ClientRefb).HasMaxLength(15);
            entity.Property(e => e.Contact).HasMaxLength(50);
            entity.Property(e => e.CourierId).HasColumnName("CourierID");
            entity.Property(e => e.CourierPayment).HasColumnType("money");
            entity.Property(e => e.CourierPercentageOverride).HasColumnType("numeric(5, 4)");
            entity.Property(e => e.DeliverByTimeZoneId).HasColumnName("DeliverByTimeZoneID");
            entity.Property(e => e.DeliverToContact).HasMaxLength(100);
            entity.Property(e => e.DeliverToLeaveId).HasColumnName("DeliverToLeaveID");
            entity.Property(e => e.DeliverToPhone).HasMaxLength(100);
            entity.Property(e => e.DeliveryAddressLine1).HasMaxLength(255);
            entity.Property(e => e.DeliveryAddressLine2).HasMaxLength(255);
            entity.Property(e => e.DeliveryAddressLine3).HasMaxLength(255);
            entity.Property(e => e.DeliveryAddressLine4).HasMaxLength(255);
            entity.Property(e => e.DeliveryAddressLine5).HasMaxLength(255);
            entity.Property(e => e.DeliveryAddressLine6).HasMaxLength(255);
            entity.Property(e => e.DeliveryAddressLine7).HasMaxLength(255);
            entity.Property(e => e.DeliveryAddressLine8).HasMaxLength(255);
            entity.Property(e => e.DeliveryLatitude).HasMaxLength(50);
            entity.Property(e => e.DeliveryLongitude).HasMaxLength(50);
            entity.Property(e => e.Done).HasAnnotation("Relational:DefaultConstraintName", "DF__tblBulkJob__Done__30992191");
            entity.Property(e => e.DropOffLocationId).HasColumnName("DropOffLocationID");
            entity.Property(e => e.FromAddress).HasMaxLength(150);
            entity.Property(e => e.FromCompany).HasMaxLength(150);
            entity.Property(e => e.FromSuburb).HasMaxLength(50);
            entity.Property(e => e.Height).HasColumnType("numeric(18, 0)");
            entity.Property(e => e.InformationParentId).HasColumnName("InformationParentID");
            entity.Property(e => e.JobId).HasColumnName("JobID");
            entity.Property(e => e.JobNumber).HasMaxLength(50);
            entity.Property(e => e.JobRelationshipTypeId).HasColumnName("JobRelationshipTypeID");
            entity.Property(e => e.JobStatus).HasAnnotation("Relational:DefaultConstraintName", "DF__tblBulkJo__JobSt__2EB0D91F");
            entity.Property(e => e.Length).HasColumnType("numeric(18, 0)");
            entity.Property(e => e.LinehaulRunId).HasColumnName("LinehaulRunID");
            entity.Property(e => e.LoggedInContactId).HasColumnName("LoggedInContactID");
            entity.Property(e => e.Manifest).HasMaxLength(50);
            entity.Property(e => e.MultiboxParentId).HasColumnName("MultiboxParentID");
            entity.Property(e => e.Notes).HasMaxLength(4000);
            entity.Property(e => e.NwdocJob).HasColumnName("NWDocJob");
            entity.Property(e => e.OnHold).HasAnnotation("Relational:DefaultConstraintName", "DF__tblBulkJo__OnHol__2FA4FD58");
            entity.Property(e => e.OrderRef).HasMaxLength(50);
            entity.Property(e => e.OurRef).HasMaxLength(20);
            entity.Property(e => e.ParentId).HasColumnName("ParentID");
            entity.Property(e => e.PickUpLatitude).HasMaxLength(50);
            entity.Property(e => e.PickUpLongitude).HasMaxLength(50);
            entity.Property(e => e.PickupAddressLine1).HasMaxLength(255);
            entity.Property(e => e.PickupAddressLine2).HasMaxLength(255);
            entity.Property(e => e.PickupAddressLine3).HasMaxLength(255);
            entity.Property(e => e.PickupAddressLine4).HasMaxLength(255);
            entity.Property(e => e.PickupAddressLine5).HasMaxLength(255);
            entity.Property(e => e.PickupAddressLine6).HasMaxLength(255);
            entity.Property(e => e.PickupAddressLine7).HasMaxLength(255);
            entity.Property(e => e.PickupAddressLine8).HasMaxLength(255);
            entity.Property(e => e.PickupFromContact).HasMaxLength(100);
            entity.Property(e => e.PickupFromPhone).HasMaxLength(100);
            entity.Property(e => e.PickupReadyDateTime).HasColumnType("datetime");
            entity.Property(e => e.PickupTimeZoneId).HasColumnName("PickupTimeZoneID");
            entity.Property(e => e.ProofOfDeliveryEmail).HasMaxLength(500);
            entity.Property(e => e.ProofOfDeliveryMobile).HasMaxLength(100);
            entity.Property(e => e.RegionId).HasColumnName("RegionID");
            entity.Property(e => e.RootParentId).HasColumnName("RootParentID");
            entity.Property(e => e.RunName).HasMaxLength(50);
            entity.Property(e => e.ScheduleId).HasColumnName("ScheduleID");
            entity.Property(e => e.ScheduleName).HasMaxLength(200);
            entity.Property(e => e.ShopRef1).HasMaxLength(50);
            entity.Property(e => e.ShopRef2).HasMaxLength(50);
            entity.Property(e => e.ShopRef3).HasMaxLength(50);
            entity.Property(e => e.ShopRef4).HasMaxLength(50);
            entity.Property(e => e.ShopRef5).HasMaxLength(50);
            entity.Property(e => e.SourceId).HasColumnName("SourceID");
            entity.Property(e => e.StripeChargeId)
                .HasMaxLength(50)
                .HasColumnName("StripeChargeID");
            entity.Property(e => e.ToAddress).HasMaxLength(150);
            entity.Property(e => e.ToCompany).HasMaxLength(150);
            entity.Property(e => e.ToSuburb).HasMaxLength(50);
            entity.Property(e => e.TotalDistance).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.TrackingEmail).HasMaxLength(500);
            entity.Property(e => e.TrackingMobile).HasMaxLength(500);
            entity.Property(e => e.Void).HasAnnotation("Relational:DefaultConstraintName", "DF__tblBulkJob__Void__318D45CA");
            entity.Property(e => e.Weight).HasColumnType("decimal(6, 2)");
            entity.Property(e => e.Width).HasColumnType("numeric(18, 0)");
        });

        modelBuilder.Entity<TblBulkJobRun>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tblBulkJ__3214EC2739E294A9");

            entity.ToTable("tblBulkJobRun");

            entity.HasIndex(e => e.BulkJobId, "IX_tblBulkJobRun_BulkJobID");

            entity.HasIndex(e => e.RunId, "RunID-NonClusteredIndex-20190824-171500");

            entity.HasIndex(e => e.BulkJobId, "index_BulkJobID");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.BulkJobId).HasColumnName("BulkJobID");
            entity.Property(e => e.RunId).HasColumnName("RunID");

            entity.HasOne(d => d.BulkJob).WithMany(p => p.TblBulkJobRuns)
                .HasForeignKey(d => d.BulkJobId)
                .HasConstraintName("FK__tblBulkJo__BulkJ__0876219E");

            entity.HasOne(d => d.Run).WithMany(p => p.TblBulkJobRuns)
                .HasForeignKey(d => d.RunId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__tblBulkJo__RunID__3F954511");
        });

        modelBuilder.Entity<TblBulkRun>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tblBulkR__3214EC274CF5691D");

            entity.ToTable("tblBulkRun");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CourierId).HasColumnName("CourierID");
            entity.Property(e => e.Created)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__tblBulkRu__Creat__355DD6AE")
                .HasColumnType("datetime");
            entity.Property(e => e.DespatchDateTime).HasColumnType("datetime");
            entity.Property(e => e.LastModified)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__tblBulkRu__LastM__3651FAE7")
                .HasColumnType("datetime");
            entity.Property(e => e.Name).HasMaxLength(50);
            entity.Property(e => e.Payout).HasColumnType("money");
            entity.Property(e => e.Revenue).HasColumnType("money");
            entity.Property(e => e.Status)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__tblBulkRu__Statu__3469B275");
        });

        modelBuilder.Entity<ZipPolygon>(entity =>
        {
            entity.HasKey(e => e.ZipPolygonId).HasName("PK__ZipPolyg__6A8AEEE3127F7A1C");

            entity.ToTable("ZipPolygon");

            entity.Property(e => e.ZipPolygonId).HasColumnName("ZipPolygonID");
            entity.Property(e => e.Latitude).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.Longitude).HasColumnType("decimal(18, 8)");
            entity.Property(e => e.Wkt).HasColumnName("WKT");
            entity.Property(e => e.Zip)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<ZoneCombo>(entity =>
        {
            entity.HasKey(e => e.ZoneComboId).HasName("PK__ZoneComb__1250D47322EAEC0F");

            entity.ToTable("ZoneCombo");

            entity.Property(e => e.ZoneComboId).HasColumnName("ZoneComboID");
            entity.Property(e => e.ChargeRate).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.ClientId).HasColumnName("ClientID");
            entity.Property(e => e.Created)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__ZoneCombo__Creat__24D33481")
                .HasColumnType("datetime");
            entity.Property(e => e.CreatedBy).HasMaxLength(255);
            entity.Property(e => e.DriverRate).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.ExtraChargeId).HasColumnName("ExtraChargeID");
            entity.Property(e => e.FromZoneZipId).HasColumnName("FromZoneZipID");
            entity.Property(e => e.LastModified)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__ZoneCombo__LastM__25C758BA")
                .HasColumnType("datetime");
            entity.Property(e => e.LastModifiedBy).HasMaxLength(255);
            entity.Property(e => e.RateCardId).HasColumnName("RateCardID");
            entity.Property(e => e.SpeedId).HasColumnName("SpeedID");
            entity.Property(e => e.ToZoneZipId).HasColumnName("ToZoneZipID");
            entity.Property(e => e.VehicleSizeId).HasColumnName("VehicleSizeID");
            entity.Property(e => e.WeightFrom).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.WeightTo).HasColumnType("decimal(18, 4)");
            entity.Property(e => e.ZoneComboName).HasMaxLength(255);

            entity.HasOne(d => d.FromZoneZip).WithMany(p => p.ZoneComboFromZoneZips)
                .HasForeignKey(d => d.FromZoneZipId)
                .HasConstraintName("FK__ZoneCombo__LastM__26BB7CF3");

            entity.HasOne(d => d.ToZoneZip).WithMany(p => p.ZoneComboToZoneZips)
                .HasForeignKey(d => d.ToZoneZipId)
                .HasConstraintName("FK__ZoneCombo__ToZon__27AFA12C");
        });

        modelBuilder.Entity<ZoneGroup>(entity =>
        {
            entity.HasKey(e => e.ZoneGroupId).HasName("PK__ZoneGrou__958F80BF0189F844");

            entity.ToTable("ZoneGroup");

            entity.HasIndex(e => e.ClearListAreaId, "IX_ZoneGroup_ClearListAreaId");

            entity.Property(e => e.ZoneGroupId).HasColumnName("ZoneGroupID");
            entity.Property(e => e.Created)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__ZoneGroup__Creat__037240B6")
                .HasColumnType("datetime");
            entity.Property(e => e.CreatedBy).HasMaxLength(255);
            entity.Property(e => e.LastModified)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__ZoneGroup__LastM__046664EF")
                .HasColumnType("datetime");
            entity.Property(e => e.LastModifiedBy).HasMaxLength(255);
            entity.Property(e => e.Name).HasMaxLength(255);
        });

        modelBuilder.Entity<ZoneName>(entity =>
        {
            entity.HasKey(e => e.ZoneNameId).HasName("PK__ZoneName__86588D1C0742D19A");

            entity.ToTable("ZoneName");

            entity.Property(e => e.ZoneNameId).HasColumnName("ZoneNameID");
            entity.Property(e => e.Created)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__ZoneName__Create__092B1A0C")
                .HasColumnType("datetime");
            entity.Property(e => e.CreatedBy).HasMaxLength(255);
            entity.Property(e => e.GeoPolygonId).HasColumnName("GeoPolygonID");
            entity.Property(e => e.LastModified)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__ZoneName__LastMo__0A1F3E45")
                .HasColumnType("datetime");
            entity.Property(e => e.LastModifiedBy).HasMaxLength(255);
            entity.Property(e => e.LocationId).HasColumnName("LocationID");
            entity.Property(e => e.ZoneGroupId).HasColumnName("ZoneGroupID");
            entity.Property(e => e.ZoneName1)
                .HasMaxLength(255)
                .HasColumnName("ZoneName");

            entity.HasOne(d => d.ZoneGroup).WithMany(p => p.ZoneNames)
                .HasForeignKey(d => d.ZoneGroupId)
                .HasConstraintName("FK__ZoneName__LastMo__0B13627E");
        });

        modelBuilder.Entity<ZoneZip>(entity =>
        {
            entity.HasKey(e => e.ZoneZipId).HasName("PK__ZoneZip__76E657120DEFCF29");

            entity.ToTable("ZoneZip");

            entity.Property(e => e.ZoneZipId).HasColumnName("ZoneZipID");
            entity.Property(e => e.ClientId).HasColumnName("ClientID");
            entity.Property(e => e.Created)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__ZoneZip__Created__0FD8179B")
                .HasColumnType("datetime");
            entity.Property(e => e.CreatedBy).HasMaxLength(255);
            entity.Property(e => e.LastModified)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__ZoneZip__LastMod__10CC3BD4")
                .HasColumnType("datetime");
            entity.Property(e => e.LastModifiedBy).HasMaxLength(255);
            entity.Property(e => e.Zip)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.ZoneNameId).HasColumnName("ZoneNameID");
            entity.Property(e => e.ZoneZipGroupId).HasColumnName("ZoneZipGroupID");

            entity.HasOne(d => d.ZoneName).WithMany(p => p.ZoneZips)
                .HasForeignKey(d => d.ZoneNameId)
                .HasConstraintName("FK__ZoneZip__LastMod__11C0600D");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}