// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RunBuilder.Models
{
    public partial class RVW_stpBulkSpeedsResult
    {
        public int SpeedId { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
    }
}
