// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RunBuilder.Models
{
    public partial class RVW_stpBulkRegionsResult
    {
        public int siteID { get; set; }
        [StringLength(150)]
        public string Name { get; set; }
        public bool Active { get; set; }
    }
}
