// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RunBuilder.Models;

public partial class TblBulkJob
{
    public int BulkJobId { get; set; }

    public string JobNumber { get; set; }

    public DateTime BookDate { get; set; }

    public DateTime BookTime { get; set; }

    public int JobStatus { get; set; }

    public int ClientId { get; set; }

    public string ClientCode { get; set; }

    public string Contact { get; set; }

    public decimal? Amount { get; set; }

    public int Speed { get; set; }

    public string FromCompany { get; set; }

    public string FromAddress { get; set; }

    public string FromSuburb { get; set; }

    public int? FromPostCode { get; set; }

    public string ToCompany { get; set; }

    public string ToAddress { get; set; }

    public string ToSuburb { get; set; }

    public int? ToPostCode { get; set; }

    public int? Size { get; set; }

    public short? Qty { get; set; }

    public decimal? Weight { get; set; }

    public int? CourierId { get; set; }

    public string ClientRefa { get; set; }

    public string ClientRefb { get; set; }

    public string OurRef { get; set; }

    public bool? DeliverToPrivateBusiness { get; set; }

    public int? DeliverToLeaveId { get; set; }

    public string Notes { get; set; }

    public bool? RemoteJob { get; set; }

    public int? TrackingMethod { get; set; }

    public string TrackingEmail { get; set; }

    public string TrackingMobile { get; set; }

    public string ProofOfDeliveryMobile { get; set; }

    public string ProofOfDeliveryEmail { get; set; }

    public string PickUpLatitude { get; set; }

    public string PickUpLongitude { get; set; }

    public string DeliveryLatitude { get; set; }

    public string DeliveryLongitude { get; set; }

    public bool? PrebookJob { get; set; }

    public bool OnHold { get; set; }

    public bool? WellingtonJob { get; set; }

    public bool? NwdocJob { get; set; }

    public bool Done { get; set; }

    public bool Void { get; set; }

    public int? JobId { get; set; }

    public string DeliverToContact { get; set; }

    public string DeliverToPhone { get; set; }

    public string RunName { get; set; }

    public int? FromGeoType { get; set; }

    public int? ToGeoType { get; set; }

    public string Manifest { get; set; }

    public int? RunOrder { get; set; }

    public int? BulkRunId { get; set; }

    public int? ImportId { get; set; }

    public bool? Multibox { get; set; }

    public decimal? Length { get; set; }

    public decimal? Width { get; set; }

    public decimal? Height { get; set; }

    public int? MultiboxParentId { get; set; }

    public decimal? CourierPayment { get; set; }

    public bool? SortScan { get; set; }

    public bool? RunScan { get; set; }

    public int? ScheduleId { get; set; }

    public string OrderRef { get; set; }

    public int? ShopId { get; set; }

    public string ShopRef1 { get; set; }

    public string ShopRef2 { get; set; }

    public string ShopRef3 { get; set; }

    public string ShopRef4 { get; set; }

    public string ShopRef5 { get; set; }

    public int? RegionId { get; set; }

    public int? LinehaulRunId { get; set; }

    public int? StorageState { get; set; }

    public int? DeliveryState { get; set; }

    public string Barcode { get; set; }

    public int? JobRelationshipTypeId { get; set; }

    public int? ParentId { get; set; }

    public int? InformationParentId { get; set; }

    public int? RootParentId { get; set; }

    public int? SourceId { get; set; }

    public string StripeChargeId { get; set; }

    public DateTime? PickupReadyDateTime { get; set; }

    public string ScheduleName { get; set; }

    public int? LoggedInContactId { get; set; }

    public int? DropOffLocationId { get; set; }

    public decimal? CourierPercentageOverride { get; set; }

    public string ClientItemIds { get; set; }

    public int? BulkParentId { get; set; }

    public bool? DocRequired { get; set; }

    public string PickupAddressLine1 { get; set; }

    public string PickupAddressLine2 { get; set; }

    public string PickupAddressLine3 { get; set; }

    public string PickupAddressLine4 { get; set; }

    public string PickupAddressLine5 { get; set; }

    public string PickupAddressLine6 { get; set; }

    public string PickupAddressLine7 { get; set; }

    public string PickupAddressLine8 { get; set; }

    public string DeliveryAddressLine1 { get; set; }

    public string DeliveryAddressLine2 { get; set; }

    public string DeliveryAddressLine3 { get; set; }

    public string DeliveryAddressLine4 { get; set; }

    public string DeliveryAddressLine5 { get; set; }

    public string DeliveryAddressLine6 { get; set; }

    public string DeliveryAddressLine7 { get; set; }

    public string DeliveryAddressLine8 { get; set; }

    public string PickupFromContact { get; set; }

    public string PickupFromPhone { get; set; }

    public int? PickupTimeZoneId { get; set; }

    public decimal? TotalDistance { get; set; }

    public int? DeliverByTimeZoneId { get; set; }

    public virtual ICollection<TblBulkJobRun> TblBulkJobRuns { get; set; } = new List<TblBulkJobRun>();
}