// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RunBuilder.Models;

public partial class TblBulkRun
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? Mins { get; set; }

    public double? Kms { get; set; }

    public int? CourierId { get; set; }

    public int? Status { get; set; }

    public decimal? Revenue { get; set; }

    public decimal? Payout { get; set; }

    public double? CourierPercentage { get; set; }

    public string GoogleRouteResponse { get; set; }

    public DateTime? Created { get; set; }

    public DateTime? LastModified { get; set; }

    public DateTime? DespatchDateTime { get; set; }

    public virtual ICollection<TblBulkJobRun> TblBulkJobRuns { get; set; } = new List<TblBulkJobRun>();
}