// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RunBuilder.Models;

public partial class TblBulkJobRun
{
    public int Id { get; set; }

    public int? RunId { get; set; }

    public int? BulkJobId { get; set; }

    public int? PickRunOrder { get; set; }

    public virtual TblBulkJob BulkJob { get; set; }

    public virtual TblBulkRun Run { get; set; }
}