// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace RunBuilder.Models
{
    public partial class UTL_stpCourier_ActiveResult
    {
        public int courierID { get; set; }
        public string courier { get; set; }
        public string Fleet { get; set; }
    }
}
