// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RunBuilder.Models
{
    public partial class UTL_stpJob_tblBulkJobResult
    {
        public int BulkJobID { get; set; }
        public int ClientID { get; set; }
        [StringLength(5)]
        public string ClientCode { get; set; }
        [StringLength(50)]
        public string JobNumber { get; set; }
        [StringLength(30)]
        public string DeliveryDate { get; set; }
        [StringLength(30)]
        public string ReadyTime { get; set; }
        public int JobStatus { get; set; }
        [StringLength(150)]
        public string CompanyName { get; set; }
        [StringLength(150)]
        public string ToAddress { get; set; }
        [StringLength(50)]
        public string ToSuburb { get; set; }
        public int ToPostCode { get; set; }
        public int? CourierID { get; set; }
        [StringLength(150)]
        public string FromCompany { get; set; }
        [StringLength(150)]
        public string FromAddress { get; set; }
        [StringLength(50)]
        public string FromSuburb { get; set; }
        public int? FromPostCode { get; set; }
        [StringLength(50)]
        public string Contact { get; set; }
        [Column("Amount", TypeName = "money")]
        public decimal Amount { get; set; }
        public int SpeedID { get; set; }
        public int? Size { get; set; }
        public short? Items { get; set; }
        [Column("Weight", TypeName = "decimal(6,2)")]
        public decimal? Weight { get; set; }
        public bool? RemoteScreen { get; set; }
        [StringLength(20)]
        public string ClientRefa { get; set; }
        [StringLength(15)]
        public string ClientRefb { get; set; }
        [StringLength(20)]
        public string OurRef { get; set; }
        [StringLength(100)]
        public string DeliverToContact { get; set; }
        [StringLength(100)]
        public string DeliverToPhone { get; set; }
        public bool? Ok_To_Leave { get; set; }
        public int? Location { get; set; }
        [StringLength(4000)]
        public string Notes { get; set; }
        public int? TrackingMethod { get; set; }
        [StringLength(500)]
        public string TrackingEmail { get; set; }
        [StringLength(500)]
        public string TrackingMobile { get; set; }
        [StringLength(100)]
        public string Mobile { get; set; }
        [StringLength(500)]
        public string Email { get; set; }
        public double? fromLat { get; set; }
        public double? fromLng { get; set; }
        public double? toLat { get; set; }
        public double? toLng { get; set; }
        public bool? PrebookJob { get; set; }
        public bool? WellingtonJob { get; set; }
        public bool? NWDocJob { get; set; }
        public bool Done { get; set; }
        public bool Void { get; set; }
        public int? FromGeoType { get; set; }
        public int? ToGeoType { get; set; }
        [StringLength(50)]
        public string RunName { get; set; }
        public int BulkJobRunID { get; set; }
        [StringLength(101)]
        public string Courier { get; set; }
        public int? BuilderIndex { get; set; }
        [StringLength(50)]
        public string PrefixRunName { get; set; }
        [StringLength(50)]
        public string PostCodeMergeTo { get; set; }
        public int RunSequence { get; set; }
        public int MaxJobsPerRun { get; set; }
    }
}
