// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RunBuilder.Models
{
    public partial class UTL_stpJob_tblBulkRunSettingsResult
    {
        public int ClientID { get; set; }
        [StringLength(5)]
        public string ClientCode { get; set; }
    }
}
