// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RunBuilder.Models
{
    public partial class UTL_stpJob_tblBulkRunWithFilterResult
    {
        public int ID { get; set; }
        [StringLength(50)]
        public string name { get; set; }
        public int? CourierID { get; set; }
        [StringLength(101)]
        public string Courier { get; set; }
        [StringLength(9)]
        public string CourierPercentage { get; set; }
        public int? Mins { get; set; }
        public double? Kms { get; set; }
        public int BulkJobID { get; set; }
        public int RunOrder { get; set; }
        [StringLength(50)]
        public string Fleet { get; set; }
        public int Status { get; set; }
    }
}
