// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RunBuilder.Models;

public partial class ZoneZip
{
    public int ZoneZipId { get; set; }

    public int? ZoneNumber { get; set; }

    public int? ZoneNameId { get; set; }

    public string Zip { get; set; }

    public int? ClientId { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? Created { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime? LastModified { get; set; }

    public bool? ApplyCongestion { get; set; }

    public int? ZoneZipGroupId { get; set; }

    public virtual ICollection<ZoneCombo> ZoneComboFromZoneZips { get; set; } = new List<ZoneCombo>();

    public virtual ICollection<ZoneCombo> ZoneComboToZoneZips { get; set; } = new List<ZoneCombo>();

    public virtual ZoneName ZoneName { get; set; }
}