// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RunBuilder.Models;

public partial class ZoneCombo
{
    public int ZoneComboId { get; set; }

    public int? ClientId { get; set; }

    public int? FromZoneZipId { get; set; }

    public int? ToZoneZipId { get; set; }

    public int? SpeedId { get; set; }

    public int? VehicleSizeId { get; set; }

    public decimal? ChargeRate { get; set; }

    public decimal? DriverRate { get; set; }

    public int? ExtraChargeId { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? Created { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime? LastModified { get; set; }

    public string ZoneComboName { get; set; }

    public bool? ApplyChargeRateFuel { get; set; }

    public int? RateCardId { get; set; }

    public bool? Active { get; set; }

    public decimal? WeightFrom { get; set; }

    public decimal? WeightTo { get; set; }

    public virtual ZoneZip FromZoneZip { get; set; }

    public virtual ZoneZip ToZoneZip { get; set; }
}