// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RunBuilder.Models;

public partial class ZoneName
{
    public int ZoneNameId { get; set; }

    public string ZoneName1 { get; set; }

    public int? GeoPolygonId { get; set; }

    public int? ZoneGroupId { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? Created { get; set; }

    public string LastModifiedBy { get; set; }

    public DateTime? LastModified { get; set; }

    public int? LocationId { get; set; }

    public virtual ZoneGroup ZoneGroup { get; set; }

    public virtual ICollection<ZoneZip> ZoneZips { get; set; } = new List<ZoneZip>();
}